---
- name: Create the /var/cyhy/cyhy-mailer directory
  ansible.builtin.file:
    group: "{{ cyhy_mailer_file_owner_group | default(omit) }}"
    mode: 0755
    owner: "{{ cyhy_mailer_file_owner_username | default(omit) }}"
    path: /var/cyhy/cyhy-mailer
    state: directory

- name: Copy Docker Compose files to the /var/cyhy/cyhy-mailer directory
  ansible.builtin.copy:
    dest: /var/cyhy/cyhy-mailer
    group: "{{ cyhy_mailer_file_owner_group | default(omit) }}"
    mode: 0644
    owner: "{{ cyhy_mailer_file_owner_username | default(omit) }}"
    src: "{{ item }}"
  loop:
    - docker-compose.bod.yml
    - docker-compose.cyhy-notification.yml
    - docker-compose.cyhy.yml
    - docker-compose.yml
