---
# tasks file for cyhy_mailer
- name: Create the /var/cyhy/cyhy-mailer directory
  file:
    path: /var/cyhy/cyhy-mailer
    state: directory
    mode: 0755

- name: Download and untar the cyhy-mailer tarball
  # ansible-lint E208 gives an error if we don't specify the mode,
  # but we definitely don't want to do that here since it will
  # override the permissions on the files in the archive.
  unarchive: # noqa 208
    src: https://api.github.com/repos/cisagov/cyhy-mailer/tarball/develop
    dest: /var/cyhy/cyhy-mailer
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
