---
- name: Create the /var/cyhy/cyhy-mailer directory
  file:
    group: "{{ file_owner_group | default(omit) }}"
    mode: 0755
    owner: "{{ file_owner_username | default(omit) }}"
    path: /var/cyhy/cyhy-mailer
    state: directory

- name: Download and untar the cyhy-mailer tarball
  unarchive:
    dest: /var/cyhy/cyhy-mailer
    extra_opts:
      - "--strip-components=1"
    group: "{{ file_owner_group | default(omit) }}"
    owner: "{{ file_owner_username | default(omit) }}"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/cyhy-mailer/tarball/develop
