---
- name: Create the /var/cyhy/cyhy-mailer directory
  file:
    path: /var/cyhy/cyhy-mailer
    state: directory
    mode: 0755

- name: Download and untar the cyhy-mailer tarball
  unarchive:
    src: https://api.github.com/repos/cisagov/cyhy-mailer/tarball/develop
    dest: /var/cyhy/cyhy-mailer
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
