---
- name: Create the /var/cyhy/cyhy-mailer directory
  file:
    mode: 0755
    path: /var/cyhy/cyhy-mailer
    state: directory

- name: Download and untar the cyhy-mailer tarball
  unarchive:
    dest: /var/cyhy/cyhy-mailer
    extra_opts:
      - "--strip-components=1"
    remote_src: yes
    src: https://api.github.com/repos/cisagov/cyhy-mailer/tarball/develop
